import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TableComponent from '../components/Table'
import FormComponent from '../components/Form'
import axios from 'axios'
import React, {useState, useEffect } from "react";
import { StoreContextProvider } from '../hooks/store'
import { useRouter } from 'next/router'

const Home = ({ datatables }) => {
  const [data, setData] = useState(datatables);
  const {query} = useRouter();

  const updateData = async() => {
    const params = new URLSearchParams(query).toString();
    const res = await fetch(`/api/audit-log?${params}`)
    const datatables = await res.json();
    setData(datatables);
  }
  useEffect(() => {
    updateData()
  }, [query])
  return (
    <div className={styles.container}>
      <Head>
        <title>Estarta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <StoreContextProvider>
          <FormComponent/>
          <TableComponent datatables={data}/>
        </StoreContextProvider>
      </main>
    </div>
  )
}

export const getServerSideProps = async (props) => {
  const {req} = props;
  const res = await fetch(`${process.env.PROTOCOL}://${req.headers.host}/api/audit-log`)
  const datatables = await res.json()

  return {
    props: {
      datatables: datatables,
    },
  }
}

export default Home